// ExerciseLibrary.swift
// FemFit – Komplette Übungs-Bibliothek (400+ Übungen)

import Foundation

enum MuscleGroup: String, CaseIterable {
    case brust = "Brust"
    case schulter = "Schulter"
    case trizeps = "Trizeps"
    case ruecken = "Rücken"
    case bizeps = "Bizeps"
    case unterarm = "Unterarm"
    case beine = "Beine"
    case gluteus = "Gluteus"
    case bauch = "Bauch"

    var emoji: String {
        switch self {
        case .brust:    return "🫁"
        case .schulter: return "🏋️"
        case .trizeps:  return "💪"
        case .ruecken:  return "🔙"
        case .bizeps:   return "💪"
        case .unterarm: return "🦾"
        case .beine:    return "🦵"
        case .gluteus:  return "🍑"
        case .bauch:    return "🎯"
        }
    }
}

struct LibraryExercise: Identifiable {
    let id = UUID()
    let name: String
    let muscleGroup: MuscleGroup
}

// Hilfsfunktion damit der Code kürzer bleibt
private func ex(_ name: String, _ group: MuscleGroup) -> LibraryExercise {
    LibraryExercise(name: name, muscleGroup: group)
}

struct ExerciseLibrary {

    static let all: [LibraryExercise] =
        brust + schulter + trizeps + ruecken + bizeps + unterarm + beine + gluteus + bauch

    static let brust: [LibraryExercise] = [
        ex("Banded Bar Dips", .brust),
        ex("Bankdrücken Kurzhantel schräg (45 Grad)", .brust),
        ex("Bankdrücken Langhantel Flachbank", .brust),
        ex("Bankdrücken Langhantel Schrägbank", .brust),
        ex("Brust Dips", .brust),
        ex("Brust Dips am Gravitron-Gerät", .brust),
        ex("Brustpresse am Kabelzug auf der Flachbank", .brust),
        ex("Brustpresse am Kabelzug stehend", .brust),
        ex("Brustpresse liegend mit Band", .brust),
        ex("Brustpresse liegend mit Kurzhanteln einarmig", .brust),
        ex("Brustpresse Maschine liegend", .brust),
        ex("Brustpresse Maschine Schrägbank", .brust),
        ex("Butterfly am Gerät", .brust),
        ex("Butterfly am Gerät - einarmig", .brust),
        ex("Butterfly Kurzhantel Schrägbank Negativ", .brust),
        ex("Butterfly mit Kurzhantel auf der Flachbank", .brust),
        ex("Butterfly-Übung für die Brust mit gebeugtem Arm", .brust),
        ex("Crossover Frontheben am Kabelzug beidarmig", .brust),
        ex("Einarmige Hammer Strength Schrägbankbrustpresse", .brust),
        ex("Flachbankdrücken an der Multipresse (Smith-Maschine)", .brust),
        ex("Fliegende auf der Schrägbank mit Kurzhanteln (45 Grad)", .brust),
        ex("Frauenliegestütze", .brust),
        ex("Frontheben Kurzhantel auf der Schrägbank mit Untergriff", .brust),
        ex("Hammer Strength Schrägbankbrustpresse", .brust),
        ex("Kabelziehen über Kreuz (vorgebeugt)", .brust),
        ex("Kabelzug über Kreuz auf der Schrägbank", .brust),
        ex("Kabelzug über Kreuz stehend", .brust),
        ex("Knieende Liegestütze", .brust),
        ex("Kurzhantel Bankdrücken Negativ", .brust),
        ex("Kurzhantel-Fliegende auf dem Boden", .brust),
        ex("Kurzhantel-Fly auf der Schrägbank (30 Grad)", .brust),
        ex("Kurzhanteldrücken auf der Flachbank", .brust),
        ex("Langhantel-Pullover", .brust),
        ex("Liegendes Bankdrücken am Boden", .brust),
        ex("Liegestütze klassisch", .brust),
        ex("Liegestütze mit Ball", .brust),
        ex("Liegestütze mit Band", .brust),
        ex("Liegestütze mit Band und Schritt zur Seite", .brust),
        ex("Liegestütze mit engem Griff", .brust),
        ex("Liegestütze mit Klatschen", .brust),
        ex("Liegestützen mit Push-Up-Bars", .brust),
        ex("Negativ Fliegende am Kabelzug", .brust),
        ex("Schrägbank-Svend-Press mit Kurzhanteln", .brust),
        ex("Schrägbankdrücken (30°) einarmig mit Kurzhanteln", .brust),
        ex("Schrägbankdrücken Kurzhanteln (30 Grad)", .brust),
        ex("Schrägbankdrücken Langhantel negativ in der Multipresse", .brust),
        ex("Schrägbankdrücken mit Kurzhanteln (Innendrehung)", .brust),
        ex("Schrägbankdrücken Smith-Maschine", .brust),
        ex("Schräge Brustpresse Maschine", .brust),
        ex("Svend Press Landmine stehend", .brust),
        ex("Svend Press mit Kurzhanteln liegend", .brust),
        ex("Svend Press stehend", .brust),
        ex("Überzüge Brust Maschine (Pull-Over)", .brust),
        ex("Überzüge mit der Kurzhantel (Griff oben)", .brust),
        ex("Überzüge mit Kurzhantel oberer Griff", .brust),
        ex("Überzüge und Bankdrücken mit der Langhantel", .brust),
        ex("Wandliegestütze", .brust),
    ]

    static let schulter: [LibraryExercise] = [
        ex("Armheben mit Band", .schulter),
        ex("Arnold Press sitzend", .schulter),
        ex("Auf Flachbank liegendes Seitenheben im Hammergriff", .schulter),
        ex("Aufrechtes Rudern mit Band", .schulter),
        ex("Aufrechtes Rudern mit Kurzhanteln", .schulter),
        ex("Außenrotation der Schulter im Stehen mit Trainingsband", .schulter),
        ex("Außenrotation der Schulter um 90° im Stehen mit Trainingsband", .schulter),
        ex("Brustzug stehen mit Seilgriff", .schulter),
        ex("Einarmige Landminen-Schulterpresse stehend", .schulter),
        ex("Einarmiges Kurzhantel-Seitheben", .schulter),
        ex("Einarmiges Seitenheben mit Kurzhanteln stehend", .schulter),
        ex("Face Pulls mit Band", .schulter),
        ex("Fliegende einarmig an der Maschine", .schulter),
        ex("Fliegende mit Kurzhanteln auf der Schrägbank", .schulter),
        ex("Frontheben Kurzhantel abwechselnd Obergriff", .schulter),
        ex("Frontheben Langhantel", .schulter),
        ex("Frontheben am Kabelzug", .schulter),
        ex("Frontheben am Kabelzug einarmig", .schulter),
        ex("Frontheben am Kabelzug mit Seilgriff", .schulter),
        ex("Frontheben mit Gewichtscheibe und 90° Drehung", .schulter),
        ex("Frontheben mit Kurzhanteln", .schulter),
        ex("Frontheben mit Kurzhanteln sitzend (Hammergriff)", .schulter),
        ex("Innere Rotation der Schulter im Stehen mit Trainingsband", .schulter),
        ex("Kombiniertes Front- und Seitheben mit Kurzhanteln", .schulter),
        ex("Kombiniertes Seit- und Frontheben mit Kurzhanteln", .schulter),
        ex("Kurzhantel Hammer Curl und Überkopfpresse sitzend", .schulter),
        ex("Kurzhantel-Schulterdrücken stehend", .schulter),
        ex("Langhantel Schulterdrücken stehend hinter Kopf", .schulter),
        ex("Latziehen mit Kurzhanteln", .schulter),
        ex("Latziehen mit Kurzhanteln vorgebeugt mit gestreckten Armen", .schulter),
        ex("Lee Haney Kurzhantel-Rudern", .schulter),
        ex("Lee Haney Rudern an der Smith Maschine", .schulter),
        ex("Militärpresse sitzend", .schulter),
        ex("Militärpresse stehend", .schulter),
        ex("Nackendrücken Kurzhantel sitzend", .schulter),
        ex("Nackendrücken mit der Langhantel sitzend hinten", .schulter),
        ex("Overhead Pull sitzend mit Band", .schulter),
        ex("Reverse Flys mit Band", .schulter),
        ex("Rudern aufrecht am Kabelzug", .schulter),
        ex("Rudern aufrecht mit SZ Hantel", .schulter),
        ex("Schrägbank-Frontheben mit Kurzhanteln", .schulter),
        ex("Schulterdrücken Maschine", .schulter),
        ex("Seitenheben Kabelzug einarmig vorgebeugt", .schulter),
        ex("Seitenheben Maschine", .schulter),
        ex("Seitenheben mit Kurzhanteln vorgebeugt (horizontaler Griff)", .schulter),
        ex("Seitenheben sitzend mit Kurzhanteln", .schulter),
        ex("Seitenheben stehend mit Kurzhanteln", .schulter),
        ex("Seitheben Kabelzug einarmig stehend", .schulter),
        ex("Seitheben auf der Schrägbank, einarmig", .schulter),
        ex("Seitheben mit Band", .schulter),
        ex("Seitheben mit Band, einarmig kniend", .schulter),
        ex("Seitheben mit Kurzhanteln vorgebeugt (Parallelgriff)", .schulter),
        ex("Smith-Maschine Schulterdrücken in den Nacken", .schulter),
        ex("Smith-Maschine Schulterdrücken sitzend", .schulter),
        ex("Umgekehrte Fliegende am Kabelzug", .schulter),
        ex("Umgekehrte Fliegende mit Kurzhanteln auf der Schrägbank", .schulter),
        ex("Umgekehrte Fliegende sitzend am Gerät (umgekehrter Griff)", .schulter),
        ex("Umgekehrte Fliegende sitzend an Maschine", .schulter),
        ex("Vorgebeugtes Langhantelrudern an der Multipresse", .schulter),
        ex("Vorgebeugtes Langhantelrudern breiter Obergriff", .schulter),
        ex("Vorgebeugtes Rudern mit Kurzhanteln Obergriff Schrägbank", .schulter),
    ]

    static let trizeps: [LibraryExercise] = [
        ex("Bankdrücken Langhantel auf der Flachbank (enger Griff)", .trizeps),
        ex("Barrenstütze (Dips)", .trizeps),
        ex("Dips am Gravitron-Gerät mit engem Griff", .trizeps),
        ex("Einarmiges Trizepsdrücken sitzend mit Kurzhantel", .trizeps),
        ex("Einarmiges Trizepsdrücken stehend mit Kurzhantel", .trizeps),
        ex("Enge Knie-Liegestütze", .trizeps),
        ex("Enge Liegstützen Trizeps", .trizeps),
        ex("Flachbankdrücken an der Smith Maschine (enger Griff)", .trizeps),
        ex("Hammer Strength Dips im Sitzen", .trizeps),
        ex("Kurzhantel-Trizepsdrücken liegend einarmig", .trizeps),
        ex("Maschinen-Trizepsdips", .trizeps),
        ex("Stehende vorgebeugte Trizeps-Übung", .trizeps),
        ex("Triceps Kickbacks mit Band, auf einem Knie", .trizeps),
        ex("Trizeps Dips an der Bank", .trizeps),
        ex("Trizeps Extension am Kabelzug liegend", .trizeps),
        ex("Trizeps Extension am Kabelzug mit Seilgriff liegend", .trizeps),
        ex("Trizeps Extension am Kabelzug mit Seilgriff über Kopf", .trizeps),
        ex("Trizeps Extension am Kabelzug vorgebeugt", .trizeps),
        ex("Trizeps Extension am Kabelzug über Kopf", .trizeps),
        ex("Trizeps Extension mit Kurzhanteln liegend", .trizeps),
        ex("Trizeps Extension mit Langhantel stehend über Kopf", .trizeps),
        ex("Trizeps Extension mit SZ-Stange liegend", .trizeps),
        ex("Trizeps Extension mit einer Kurzhantel sitzend über Kopf", .trizeps),
        ex("Trizeps Extension mit einer Kurzhantel stehend", .trizeps),
        ex("Trizeps Kickbacks", .trizeps),
        ex("Trizeps Kickbacks Positivbank", .trizeps),
        ex("Trizeps Push Downs am Kabelzug einarmig", .trizeps),
        ex("Trizeps-Strecken am unteren Kabelzug", .trizeps),
        ex("Trizepsdrücken am Gravitron-Gerät", .trizeps),
        ex("Trizepsdrücken am Kabelzug (Push Downs)", .trizeps),
        ex("Trizepsdrücken am Kabelzug (Push Downs) im Untergriff", .trizeps),
        ex("Trizepsdrücken am Kabelzug (Push Downs) mit Seilgriff", .trizeps),
        ex("Trizepsdrücken am Kabelzug (Push Downs) mit V-Griff", .trizeps),
        ex("Trizepsdrücken an der Maschine", .trizeps),
        ex("Trizepsdrücken positiv mit der Langhantel", .trizeps),
        ex("Trizepsdrücken stehend mit Kurzhanteln", .trizeps),
        ex("Trizepsdrücken stehend mit Langhantel", .trizeps),
        ex("Trizepsdrücken stehend mit SZ-Hantel (innerer Griff)", .trizeps),
        ex("Trizepsdrücken über Kopf mit Band", .trizeps),
        ex("Trizepsstrecken über Kopf am Kabelzug vorgebeugt", .trizeps),
        ex("Umgekehrte Trizeps Push Downs am Kabelzug einarmig", .trizeps),
    ]

    static let ruecken: [LibraryExercise] = [
        ex("Beidarmiges Kurzhantelrudern Schrägbank", .ruecken),
        ex("Breite Klimmzüge zum Nacken", .ruecken),
        ex("Einarmiger Kabelzug-Überzug", .ruecken),
        ex("Einarmiges Kabelzug-Rudern im Ausfallschritt", .ruecken),
        ex("Einarmiges Rudern mit Band vorgebeugt", .ruecken),
        ex("Face-Pulls am Seilzug stehend", .ruecken),
        ex("Kabelrudern sitzend mit breitem Parallelgriff", .ruecken),
        ex("Kabelrudern stehend und vorgebeugt mit breitem Obergriff", .ruecken),
        ex("Kabelrudern stehend und vorgebeugt mit breitem Untergriff", .ruecken),
        ex("Kabelrudern stehend und vorgebeugt mit engem Obergriff", .ruecken),
        ex("Kabelrudern stehend und vorgebeugt mit engem Parallelgriff", .ruecken),
        ex("Kabelrudern stehend und vorgebeugt mit engem Untergriff", .ruecken),
        ex("Kabelrudern stehend und vorgebeugt – einarmig", .ruecken),
        ex("Klimmzüge mit Umkehrgriff", .ruecken),
        ex("Klimmzüge mit breitem Obergriff", .ruecken),
        ex("Klimmzüge mit parallelem Griff", .ruecken),
        ex("Kommando Klimmzug", .ruecken),
        ex("Kreuzheben", .ruecken),
        ex("Kurzhantelrudern beidarmig vorgebeugt", .ruecken),
        ex("Kurzhantelrudern einarmig", .ruecken),
        ex("Kurzhantelrudern vorgebeugt", .ruecken),
        ex("Langhantelrudern auf der Schrägbank", .ruecken),
        ex("Langhantelrudern im Untergriff - vorgebeugt", .ruecken),
        ex("Latziehen am Kabelzug mit breitem Griff", .ruecken),
        ex("Latziehen am Kabelzug mit engem Griff", .ruecken),
        ex("Latziehen seitlich am Kabelzug kniend", .ruecken),
        ex("Rudern am Kabelzug sitzend", .ruecken),
        ex("T-Bar Rudern", .ruecken),
    ]

    static let bizeps: [LibraryExercise] = [
        ex("Abwechelnde Bizepscurls eingedreht sitzend", .bizeps),
        ex("Abwechselnde Bizepscurls eingedreht stehend", .bizeps),
        ex("Abwechselnde Kurzhantel-Curls Schrägbank", .bizeps),
        ex("Alternierende Kurzhantel-Curls stehend", .bizeps),
        ex("Bizeps Curls am Kabelzug (Squatting)", .bizeps),
        ex("Bizeps Curls am Kabelzug - einarmig", .bizeps),
        ex("Bizeps Curls auf der Schrägbank mit Kurzhanteln", .bizeps),
        ex("Bizeps Curls mit Langhantel", .bizeps),
        ex("Bizeps Curls mit Langhantel auf der Schrägbank (Untergriff)", .bizeps),
        ex("Bizeps Curls mit der SZ-Stange stehend (enger Griff)", .bizeps),
        ex("Bizeps Scottcurls am Kabelzug einarmig", .bizeps),
        ex("Bizeps-Curl mit Band", .bizeps),
        ex("Bizeps-Curls am Kabelzug liegend (Untergriff)", .bizeps),
        ex("Bizeps-Curls sitzend", .bizeps),
        ex("Bizeps-Curls sitzend mit Innendrehung", .bizeps),
        ex("Bizeps-Curls stehend (mit Innendrehung)", .bizeps),
        ex("Bizepscurls stehend am Kabelzug", .bizeps),
        ex("Bizepscurls stehend mit Kurzhanteln", .bizeps),
        ex("Einarmige Scottcurls mit Kurzhantel stehend", .bizeps),
        ex("Hammer Curls am Kabelzug - stehend", .bizeps),
        ex("Hammer Curls sitzend", .bizeps),
        ex("Hammer Curls sitzend an der Scott-Bank (einarmig)", .bizeps),
        ex("Hammer Curls stehend beidarmig", .bizeps),
        ex("Kabelcurls am hohen Block", .bizeps),
        ex("Kabelcurls mit engem Obergriff liegend", .bizeps),
        ex("Konzentrationscurls", .bizeps),
        ex("Langhantelcurls Obergriff", .bizeps),
        ex("Scott Curls - einarmig mit Kurzhantel", .bizeps),
        ex("Scott Curls an der Maschine", .bizeps),
        ex("Scott Curls mit SZ-Stange - breiter Griff", .bizeps),
        ex("Scott-Hammercurls am Kabelzug", .bizeps),
        ex("Scott-Hammercurls mit Kurzhantel einarmig und stehend an der Schrägbank", .bizeps),
        ex("SZ-Curls sitzend", .bizeps),
        ex("Stehende Bizepscurls am Kabelzug einarmig ohne Griff", .bizeps),
        ex("Umgekehrte Curls am Kabelzug stehend", .bizeps),
        ex("Umgekehrte Curls mit Kurzhanteln - eingedreht", .bizeps),
        ex("Umgekehrte Curls stehend mit Kurzhanteln (Obergriff)", .bizeps),
        ex("Zottman Bizeps-Curl", .bizeps),
    ]

    static let unterarm: [LibraryExercise] = [
        ex("Einarmige Unterarm-Curls am Kabelzug stehend (Obergriff)", .unterarm),
        ex("Einarmige Unterarm-Curls mit Kurzhantel (Obergriff)", .unterarm),
        ex("Einarmige Unterarm-Curls mit Kurzhantel (Untergriff)", .unterarm),
        ex("Gewicht auf Stange rollen (Unterarmbeuger)", .unterarm),
        ex("Gewicht auf Stange rollen (Unterarmstrecker)", .unterarm),
        ex("Handgelenkstraining mit Hand Gripper", .unterarm),
        ex("Seitlich stehende, einarmige Unterarm-Curls am Kabelzug", .unterarm),
        ex("Stehende, einarmige Unterarm-Curls am Kabelzug", .unterarm),
        ex("Unterarm-Curls mit der Langhantel auf der Flachbank (Untergriff)", .unterarm),
        ex("Unterarm-Curls mit der Langhantel hinter dem Rücken", .unterarm),
    ]

    static let beine: [LibraryExercise] = [
        ex("Ausfallschritte", .beine),
        ex("Beinpresse", .beine),
        ex("Beinstrecker Maschine", .beine),
        ex("Beinbeuger liegend Maschine", .beine),
        ex("Bulgarian Split Squat", .beine),
        ex("Frontkniebeugen", .beine),
        ex("Goblet Squat", .beine),
        ex("Hackenschmidt-Kniebeugen", .beine),
        ex("Kniebeugen mit Langhantel", .beine),
        ex("Kniebeugen mit Kurzhanteln", .beine),
        ex("Rückausfallschritte", .beine),
        ex("Rückwärts-Ausfalltritt", .beine),
        ex("Rückwärtsausfallschritt zum einbeinigen Sprung", .beine),
        ex("Rückwärtsausfallschritte mit Drehung", .beine),
        ex("Seitliche Ausfallschritte", .beine),
        ex("Seitlicher Step-up mit seitlichem Beinheben", .beine),
        ex("Seitliches Beinheben mit Gewichten", .beine),
        ex("Senkrechtes Wadenheben Maschine", .beine),
        ex("Sissy Squat an einer Maschine", .beine),
        ex("Sprung-Kniebeugen", .beine),
        ex("Sprung-Kniebeugen mit Heelkicks", .beine),
        ex("Sprung-Kniebeugen mit Knieheben (einbeinig)", .beine),
        ex("Sprung-Kniebeugen mit Streckung", .beine),
        ex("Stehende Beinbeuger vorgebeugt", .beine),
        ex("Stehende Hüftadduktions-Maschine", .beine),
        ex("Step-Up auf Box mit Kurzhanteln", .beine),
        ex("Sumo Deadlift", .beine),
        ex("Trap Bar Kreuzheben", .beine),
        ex("Umgekehrte Hackenschmidt-Kniebeugen", .beine),
        ex("Umgekehrte Hackenschmidt-Kniebeugen mit einem Bein", .beine),
        ex("Vor- und Rückwärtsausfallschritte", .beine),
        ex("Wadenheben", .beine),
        ex("Wadenheben (Zehe nach außen)", .beine),
        ex("Wadenheben (Zehen nach innen)", .beine),
        ex("Wadenheben an der Beinpresse", .beine),
        ex("Wadenheben sitzend", .beine),
        ex("Wadenheben sitzend mit Langhantel", .beine),
        ex("Wadenheben stehend mit Langhantel", .beine),
        ex("Wechselnde Sprung-Ausfallschritte", .beine),
        ex("Überkopfkniebeuge (mit der Langhantel)", .beine),
    ]

    static let gluteus: [LibraryExercise] = [
        ex("Abduktoren Maschine", .gluteus),
        ex("Abduktoren Maschine nach vorne gelehnt", .gluteus),
        ex("Alternierende Ausfallschritte mit Langhantel (Lunges)", .gluteus),
        ex("Armstütz mit seitlicher Hüft-Abduktion und Beinstrecken mit Band", .gluteus),
        ex("Ausfallschritt nach hinten", .gluteus),
        ex("Ausfallschritt nach vorne", .gluteus),
        ex("Ausfallschritt rückwärts an der Multipresse", .gluteus),
        ex("Ausfallschritte an der Multipresse", .gluteus),
        ex("Barbell Good Mornings", .gluteus),
        ex("Beinschwünge auf allen Vieren", .gluteus),
        ex("Bridging mit alternierendem Knieheben", .gluteus),
        ex("Bulgarische Kniebeugen", .gluteus),
        ex("Diagonaler Ausfallschritt nach hinten an der Smith-Maschine", .gluteus),
        ex("Donkey Kick zur Seite mit geradem Bein", .gluteus),
        ex("Donkey Kicks mit Kurzhantel", .gluteus),
        ex("Donkey Kicks mit geradem Bein", .gluteus),
        ex("Einbeinige Gesäßbrücke", .gluteus),
        ex("Einbeinige Gesäßbrücke mit Kurzhantel", .gluteus),
        ex("Einbeinige Gesäßbrücke mit Stuhl", .gluteus),
        ex("Einbeinige Gesäßbrücke mit gestrecktem Arm", .gluteus),
        ex("Einbeinige Kniebeugen", .gluteus),
        ex("Einbeiniges Beinheben nach hinten mit kreisender Bewegung", .gluteus),
        ex("Einbeiniges Kreuzheben mit Kurzhanteln", .gluteus),
        ex("Esel-Tritt", .gluteus),
        ex("Feuerwehr-Hydrant", .gluteus),
        ex("GHD-Rückwärts-Hyperextension", .gluteus),
        ex("Gesäß-Kickbacks mit Beinstrecker und Gewichten", .gluteus),
        ex("Gesäßbrücke", .gluteus),
        ex("Gesäßbrücke mit Abduktion mit Trainingsband", .gluteus),
        ex("Gesäßbrücke mit Langhantel an der Bank", .gluteus),
        ex("Gesäßbrücke mit geradem Arm", .gluteus),
        ex("Glute Bridge an einer Maschine", .gluteus),
        ex("Glute-Kickbacks mit gebeugtem Knie und Band", .gluteus),
        ex("Hofknicks-Ausfallschritt mit Kurzhanteln", .gluteus),
        ex("Hyperextension Gesäß", .gluteus),
        ex("Hyperextensionen (Rückenstrecker) am Gerät", .gluteus),
        ex("Hyperextensions am Gerät mit Langhantel", .gluteus),
        ex("Hüftabduktion in Bauchlage mit Band", .gluteus),
        ex("Hüftabduktion sitzend mit Band", .gluteus),
        ex("Hüftheben an der Multipresse", .gluteus),
        ex("Hüftheben in Rückenlage", .gluteus),
        ex("Kick zur Seite und nach hinten im Wechsel (mit Trainingsband)", .gluteus),
        ex("Kick-Backs am Kabelzug auf der horizontalen Bank", .gluteus),
        ex("Kickbacks Po an der Maschine", .gluteus),
        ex("Kickbacks am Kabelzug einbeinig", .gluteus),
        ex("Kleine Donkey Kicks", .gluteus),
        ex("Kleiner Donkey Kick zur Seite", .gluteus),
        ex("Kniebeugen am Kabelzug", .gluteus),
        ex("Kniebeugen mit seitlichem Beinheben und Band", .gluteus),
        ex("Kniende Kniebeuge", .gluteus),
        ex("Kreuzheben", .gluteus),
        ex("Kreuzheben einbeinig", .gluteus),
        ex("Kurzhantel-Kreuzheben", .gluteus),
        ex("Langhantel-Sumo-Kniebeugen", .gluteus),
        ex("Maschinelles Hüftabduktion im Stand", .gluteus),
        ex("Plie-Kniebeuge an der Multipresse", .gluteus),
        ex("Plie-Kniebeuge mit Kurzhantel", .gluteus),
        ex("Pulsierender Donkey-Kick liegend mit Band", .gluteus),
        ex("Reverse Smith-Maschinen-Beinpresse", .gluteus),
        ex("Rumänisches Kreuzheben", .gluteus),
        ex("Rumänisches Kreuzheben an der Smith-Maschine", .gluteus),
        ex("Rumänisches Kreuzheben einbeinig", .gluteus),
        ex("Rumänisches Kreuzheben mit Kurzhanteln", .gluteus),
        ex("Rückenstreckung im Sitzen an der Maschine", .gluteus),
        ex("Rückwärtiges Beinheben auf der Bank", .gluteus),
        ex("Seitlich liegendes Beinheben mit Band (Halbkreisbewegung)", .gluteus),
        ex("Seitlicher Ausfallschritt mit dem Resistance-Band", .gluteus),
        ex("Seitliches Beinheben", .gluteus),
        ex("Seitliches Beinheben mit Band stehend", .gluteus),
        ex("Seitliches Beinheben, stehend und vorgebeugt mit Hilfsmittel", .gluteus),
        ex("Seitliches Beinkreisen auf allen Vieren mit Band", .gluteus),
        ex("Seitliches Hüftheben stehend am Kabelzug", .gluteus),
        ex("Single Beinpresse am Gravitron", .gluteus),
        ex("Smith-Maschinen-Gesäß-Kickback", .gluteus),
        ex("Split Squat mit vorderem Fuß erhöht", .gluteus),
        ex("Stehende Hüftabduktions-Maschine", .gluteus),
        ex("Stehende Hüftstoß-Maschine", .gluteus),
        ex("Stehende Hüftstreck-Maschine", .gluteus),
        ex("Superman Schere", .gluteus),
        ex("Tauchvogel", .gluteus),
        ex("Umgekehrte Box-Lunges", .gluteus),
        ex("Umgekehrte Hackenschmidt-Kniebeugen mit einem Bein", .gluteus),
        ex("Umgekehrte Hyperextensionen ohne Gerät (Boden)", .gluteus),
        ex("Umgekehrte Kabel-Torsozüge im Stehen", .gluteus),
        ex("Wand-Gesäßbrücke", .gluteus),
    ]

    static let bauch: [LibraryExercise] = [
        ex("Ab-Roller", .bauch),
        ex("AbCoaster-Crunch", .bauch),
        ex("AbCoaster-Schrägcrunch", .bauch),
        ex("Abwechselnder Zehenberührungs-Crunch", .bauch),
        ex("Alternierende Crunches", .bauch),
        ex("Bauchpresse am Gerät", .bauch),
        ex("Bauchpresse auf dem Gymnastikball", .bauch),
        ex("Bauchpresse mit Beinen auf einem Gymnastikball", .bauch),
        ex("Bauchpresse mit angehobenen Beinen und Kurzhantel", .bauch),
        ex("Bein- und Armheben in der Seitenlage", .bauch),
        ex("Beinheben am Gerät", .bauch),
        ex("Beinheben im Liegen", .bauch),
        ex("Beinschere", .bauch),
        ex("Beinschere über Hindernisse", .bauch),
        ex("Bicycle Crunch mit Band", .bauch),
        ex("Crunches Negativ", .bauch),
        ex("Crunches auf dem Boden", .bauch),
        ex("Crunches auf der Negativbank mit Faustschlagen", .bauch),
        ex("Die Kofferübung", .bauch),
        ex("Fahrrad-Crunch", .bauch),
        ex("Halbe Bauchpresse", .bauch),
        ex("Hollow Body Hold", .bauch),
        ex("Hängendes Beinheben", .bauch),
        ex("Hängendes Beinheben am Gerät seitlich", .bauch),
        ex("Hängendes Beinheben mit Drehung", .bauch),
        ex("Hüftbeugung und Knieabduktion im Liegen mit Trainingsband", .bauch),
        ex("Klappmesser mit Gymnastikball", .bauch),
        ex("Knieheben an der Dip Station", .bauch),
        ex("Knieheben auf der Bank", .bauch),
        ex("Kniende Bauchpresse am Kabelzug", .bauch),
        ex("Paralleler Barren mit gedrehtem Beinheben", .bauch),
        ex("Planke", .bauch),
        ex("Rudercrunches", .bauch),
        ex("Rumpfbeuge mit gestrecken Armen", .bauch),
        ex("Rumpfheben mit angehobenen Beinen", .bauch),
        ex("Russische Drehung mit erhobenen Füßen", .bauch),
        ex("Russische Drehungen", .bauch),
        ex("Scheibenwischer", .bauch),
        ex("Schräge Bauchpresse", .bauch),
        ex("Schräger seitlicher V-Crunch", .bauch),
        ex("Seitbeugen mit Kurzhantel", .bauch),
        ex("Seitliche Crunches liegend", .bauch),
        ex("Seitlicher Unterarmstütz", .bauch),
        ex("Sit-Ups auf der Schrägbank", .bauch),
        ex("Sterne-Crunch", .bauch),
        ex("TRX Atomic Bauchpresse", .bauch),
        ex("The L-Hang", .bauch),
        ex("The L-Hang mit angezogenen Knien", .bauch),
        ex("Toes-to-Bar", .bauch),
        ex("Umgekehrte Bauchpresse auf der Schrägbank", .bauch),
        ex("Umgekehrte Bauchpressen am Kabelzug liegend", .bauch),
        ex("Umgekehrte Bauchpressen auf der Bank", .bauch),
        ex("Umgekehrte Crunches auf der Schrägbank", .bauch),
        ex("Umgekehrte Crunches mit Gymnastikball", .bauch),
        ex("Unterarmstütz", .bauch),
        ex("Zehenspitzen Bauchpresse", .bauch),
    ]

    static func search(_ query: String, group: MuscleGroup? = nil) -> [LibraryExercise] {
        var list = group == nil ? all : all.filter { $0.muscleGroup == group }
        if !query.trimmingCharacters(in: .whitespaces).isEmpty {
            list = list.filter { $0.name.localizedCaseInsensitiveContains(query) }
        }
        return list.sorted { $0.name < $1.name }
    }
}
